{-# LANGUAGE OverloadedStrings, RecordWildCards  #-}
module PrettyPrinter.File where
import Codegen.File
import PrettyPrinter.Func
import Data.Text (Text)
import Data.Text.Prettyprint.Doc

instance Pretty CFile where
  pretty f = "// Autogenerated by MachCoq"
           <> line
           <> vcat (map (\p -> "#include \"" <> pretty p <> ".cpp\"") (_includes f)) -- #include <nat.hpp>
           <> line
           <> line
           <> vcat (map (\p -> "using namespace" <+> pretty p <> ";") (_includes f))
           <> line
           <> vcat (map pretty (_funcs f))
           <> line
