{-# LANGUAGE OverloadedStrings, RecordWildCards  #-}
module PrettyPrinter.File where
import Codegen.File
import PrettyPrinter.Decl()
import Data.Text.Prettyprint.Doc

instance Pretty CFile where
  pretty f = "// Autogenerated by MachCoq"
           <> line <> vcat (map (\p -> "#include \"" <> pretty p <> ".hpp\"") (_includes f))
           <> line
           <> line <> vcat (map (\p -> "using namespace" <+> pretty p <> ";") (_includes f))
           <> line
           <> line <> vsep (map pretty (_decls f))
