#include <iostream>
#include "benchmark.h"
#include "Fib.cpp"

using namespace nat;

int main() {
	// Benchmark, start
    tic();
	// Nats, autogenerated at Fib.cpp
	std::cout << fib(40) << std::endl;
    // Benchmark, stop
	toc();
    return 0;
}

