{-# LANGUAGE DuplicateRecordFields, OverloadedStrings  #-}
module Codegen.File where
import Parser.Mod
import Codegen.Func
import Codegen.Decl
import Data.Text (Text, append)
import Data.Text.Prettyprint.Doc

data CFile = CFile { includes :: [Text], filename :: Text, funcs :: [CFunc] }
    deriving (Eq)

instance Pretty CFile where
  pretty f = "// Autogenerated by MachCoq"
           <> line
           <> vcat (map pretty (includes f)) -- #include <stdio.h>
           <> line
           <> line
           <> vcat (map pretty (funcs f))
           <> line

std_imports = [ "#define XTL_DEFAULT_SYNTAX 'S'",

                "#include <mach7/match.hpp>",
                "#include <mach7/patterns/n+k.hpp>",
                "#include <mach7/patterns/constructor.hpp>",

                "#include <iostream>",
                "using namespace mch;" ]


toCFile :: Module -> CFile
toCFile Module { name = n, used_modules = Nothing, declarations = decls } = CFile std_imports (append ".cpp" n) cfuncs
    where cfuncs = map toCDecl decls
toCFile Module { name = n, used_modules = Just ml, declarations = decls } = CFile std_imports (append ".cpp" n) cfuncs -- TODO: implement linking
    where cfuncs = map toCDecl decls

