// Autogenerated by MCQC
#include "io.hpp"
#include "nat.hpp"
#include "prod.hpp"
#include "string.hpp"

using namespace Io;
using namespace Nat;
using namespace Prod;
using namespace String;


io<string> read_loop(nat f) {
  auto tup = until([=](auto prev) { return snd(prev) == (nat)0; }, [=](auto prev) {
    auto s = read(f, (nat)4096);
    return match(prev,
      [=](auto p) { return match(p,
        [=](auto sp, auto _) { return std::make_pair(append(sp, s), length(s)); }); },
      [=]() { return std::make_pair(s, length(s)); });
  }, some(std::make_pair(string(""), (nat)4096)));
  return fst<io<string>>(tup);
}

io<string> getLine() {
  auto s = read_loop((nat)0);
  return s;
}

io<void> input_output(string greeting) {
  print(greeting);
  auto s = getLine();
  print(string("Here is what you typed:"));
  print(s);
  return ;
}
